version: 2
jobs:
  test:
    working_directory: ~/work
    docker:
      - image: sierrezinal/nim-0.19:latest
    steps:
      - checkout
      - run:
          name: install bigints
          command: /nim-0.19.0/bin/nimble install bigints
      - run:
          name: build and test
          command: /nim-0.19.0/bin/nim c -r src/base58.nim

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only: master
